version: '3.8'
services:
  auth-db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5432']
      interval: 10s
      timeout: 10s
      retries: 5
  auth-api:
    build:
      context: ./auth/
      target: production
      dockerfile: ./dockerfile
    command: yarn start
    ports:
      - 3000:3000
    depends_on:
      - auth-db
