version: '3.8'
services:
  auth-db:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  auth-api:
    build:
      context: ./auth/
      target: development
      dockerfile: ./dockerfile
    volumes:
      - ./auth:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: yarn dev
    depends_on:
      - auth-db
  orders-db:
    image: postgres:15-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  orders-api:
    build:
      context: ./orders/
      target: development
      dockerfile: ./dockerfile
    volumes:
      - ./orders:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3030:3030
    command: yarn dev
    depends_on:
      - orders-db
